turnirv4/turnir_project/routes/routes.py
from flask import Blueprint, render_template, flash, request, jsonify, redirect, url_for, abort
from sqlalchemy import desc
from ..models.models import ParticipantsDB, FightsDB, CompetitionsDB, BacklogDB, RegistrationsDB
from ..extensions import db
import csv

home = Blueprint('home', __name__, template_folder='templates')


@home.route('/')
def home_view():
    return redirect(url_for('home.competition_start'))


@home.route('/fill_fighters')
def fill_fighters():
    with open('fighters.csv', encoding='utf8') as csvfile:
        fighters_csv_list = csv.reader(csvfile)
        for row in fighters_csv_list:
            new_fighter = ParticipantsDB(participant_first_name=row[0], participant_last_name=row[1])
            db.session.add(new_fighter)
            try:
                db.session.commit()
                print("Бойцы импортированы в ParticipantsDB")
            except Exception as e:
                print("Не получилось импортировать бойцов. Ошибка: ", e)
                db.session.rollback()
    return "результат импорта - в принт"


def fight_create_func(competition_id, round_number, final_status):
    competition_id = competition_id
    round_number = round_number
    final_status = final_status
    backlog_data = BacklogDB.query.filter_by(competition_id=competition_id, round_number=round_number).all()
    red_fighter_id = backlog_data[0].fighter_id
    blue_fighter_id = backlog_data[1].fighter_id
    new_fight = FightsDB(competition_id=competition_id, round_number=round_number, red_fighter_id=red_fighter_id,
                         blue_fighter_id=blue_fighter_id, final_status=final_status)
    db.session.add(new_fight)

    try:
        db.session.commit()
        print("создан новый бой в круге №", round_number, ". id бойцов:", red_fighter_id, " и ", blue_fighter_id)

    except Exception as e:
        print("не получилось создать новый бой. Ошибка:  ", e)
        db.session.rollback()

    return round_number

    ################################################################


def delete_backlog_records(competition_id, round_number):
    competition_id = competition_id
    round_number = round_number
    # удаляем из бэклога записи с бойцами из созданннного боя
    last_created_fight = FightsDB.query.filter_by(competition_id=competition_id, round_number=round_number).order_by(
        desc(FightsDB.fight_id)).first()
    # удаляем записи из бэклога бойцов, которые зашли в бой
    backlog_record_to_delete_red = BacklogDB.query.filter_by(competition_id=competition_id, round_number=round_number,
                                                             fighter_id=last_created_fight.red_fighter_id).order_by(
        desc(BacklogDB.fighter_id)).first()
    if backlog_record_to_delete_red is None:
        abort(404, description="No backlog record was Found with the given ID")
    else:
        db.session.delete(backlog_record_to_delete_red)
    backlog_record_to_delete_blue = BacklogDB.query.filter_by(competition_id=competition_id, round_number=round_number,
                                                              fighter_id=last_created_fight.blue_fighter_id).order_by(
        desc(BacklogDB.fighter_id)).first()
    if backlog_record_to_delete_blue is None:
        abort(404, description="No backlog record was Found with the given ID")
    else:
        db.session.delete(backlog_record_to_delete_blue)
    try:
        db.session.commit()
        print("удалены записи из бэклога. red_fighter: ", backlog_record_to_delete_red, ". blue_fighter: ",
              backlog_record_to_delete_blue)
    except Exception as e:
        print("Не удалось удалить записи из бэклога", e)
        db.session.rollback()
    ########################################################


@home.route('/competition_start/')
def competition_start():
    # создаем первый бой
    # fight_create_func(1)
    # last_created_fight = FightsDB.query.order_by(desc(FightsDB.fight_id)).first()
    return render_template('competition_start.html')


@home.route('/competition_create_new/')
def competition_create_new():
    #  создаем новое соревнование
    new_competition = CompetitionsDB()
    db.session.add(new_competition)

    try:
        db.session.commit()
        created_competition_data = CompetitionsDB.query.order_by(desc(CompetitionsDB.competition_id)).first()
        competition_id = created_competition_data.competition_id
        # создаем записи регистраций на созданное соревнование
        participant_data = ParticipantsDB.query.all()
        for participant in participant_data:
            new_registration = RegistrationsDB(participant_id=participant.participant_id, competition_id=competition_id,
                                               activity_status=1)
            db.session.add(new_registration)
            try:
                db.session.commit()
            except Exception as e:
                print("Не удалось создать запись в регистрациях", e)
                db.session.rollback()

        # помещаем всех бойцов в бэклог
        # participants_data = ParticipantsDB.query.all()
        regs_data = RegistrationsDB.query.filter_by(competition_id=competition_id).all()
        for registration in regs_data:
            reg_id = registration.reg_id
            new_backlog_record = BacklogDB(fighter_id=reg_id, competition_id=competition_id, round_number=1)
            db.session.add(new_backlog_record)
            try:
                db.session.commit()
            except Exception as e:
                print("Не удалось создать запись в бэклоге", e)
                db.session.rollback()

        # проверяем ситуацию в бэклоге в текущем и следующем раунде
        next_round_backlog_data = BacklogDB.query.filter_by(competition_id=competition_id, round_number=2).all()
        print("длина бэклога следующего раунда: ", len(next_round_backlog_data))
        # ситуация №1 в текущем раунде нет боев, а в следующем раунде есть два бойца в бэклоге. Значит следующий бой будет финальным. 
        current_backlog_data = BacklogDB.query.filter_by(competition_id=competition_id, round_number=1).all()
        if len(current_backlog_data) == 0 and len(next_round_backlog_data) == 2:
            print("следующий бой будет финальным")
            current_round_number = 2
            # создаем новый бой - финальный
            final_status = 'final'
            fight_create_func(competition_id, current_round_number, final_status)
            # удаляем из бэклога записи с бойцами
            delete_backlog_records(competition_id, current_round_number)
        # ситуация №2. Если в текущем раунде два бойца, а в следующем ноль. это тоже будет финальный бой
        elif len(current_backlog_data) == 2 and len(next_round_backlog_data) == 0:
            print("следующий бой будет финальным")
            current_round_number = 1
            final_status = 'final'
            fight_create_func(competition_id, current_round_number, final_status)
            # удаляем из бэклога записи с бойцами
            delete_backlog_records(competition_id, current_round_number)
        # ситуация №3. Если в текущем раунде один боец и в следующем один. Это тоже будет финальный бой
        elif len(current_backlog_data) == 1 and len(next_round_backlog_data) == 1:
            current_round_number = 1
            print("следующий бой будет финальным")
            final_status = 'final'
            next_round_backlog_data[0].round_number = current_round_number
            try:
                db.session.commit()
                print("изменили данные бойца из следующего круга")
            except Exception as e:
                print("не удалось переписать номер круга в записи бойца из следующего круга", e)
                db.session.rollback()
            fight_create_func(competition_id, current_round_number, final_status)
            # удаляем из бэклога записи с бойцами
            delete_backlog_records(competition_id, current_round_number)

        else:
            fight_create_func(competition_id, 1, 'not')
            # удаляем из бэклога записи с созданным боем
            last_created_fight = FightsDB.query.filter_by(competition_id=competition_id).order_by(
                desc(FightsDB.fight_id)).first()
            # удаляем записи из бэклога бойцов, которые зашли в бой
            delete_backlog_records(last_created_fight.competition_id, 1)

        return redirect(url_for('home.competition_view', competition_id=competition_id))

    except Exception as e:
        print("Не удалось создать соревнование", e)
        db.session.rollback()
        return render_template('competition_start.html')


# @home.route('/test/<int:fight_id>')
# def test(fight_id):
#   print("fight_id_test", fight_id)
#   return "testtt"

@home.route('/competition/<int:competition_id>')
def competition_view(competition_id):
    competition_id = competition_id
    # round_number = fight_create_func(round_number_prev)
    last_created_fight = FightsDB.query.filter_by(competition_id=competition_id).order_by(
        desc(FightsDB.fight_id)).first()
    print("id последнего созданного боя", last_created_fight.fight_id)
    return render_template("competition.html", fight_data=last_created_fight)


@home.route('/competition_finish/<int:fight_id>')
def finish_red(fight_id):
    fight_data = FightsDB.query.get(fight_id)
    winner_red_fighter_id = fight_data.red_fighter_id

    winner_data = ParticipantsDB.query.get(winner_red_fighter_id)
    print("winner_data", winner_data)
    return render_template("finish.html", winner_data=winner_data)


@home.route('/ajaxfile_red_fighter', methods=["POST", "GET"])
def ajaxfile_red_fighter():
    if request.method == 'POST':
        fight_id = request.form['fight_id']
        current_fight_data = FightsDB.query.get(fight_id)
        competition_id = current_fight_data.competition_id
        current_round_number = current_fight_data.round_number
        print("fight_id после нажатия ajaxfile_red_fighter", fight_id)

turnirv4/turnir_project/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
{% block head %}
    <meta charset="UTF-8">


    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.24/css/jquery.dataTables.css">

{% endblock %}
<title>{% block title %}  {% endblock %}</title>
</head>
<body>
   


    <div id="content">
        {% block content %}
        {% endblock %}
    </div> <!-- Это конец блока Content-->

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
<script>
    $(document).ready(function () {
        
    })
</script>

</body>
</html>

turnirv4/turnir_project/templates/competition.html
{% extends "base.html" %}

{% block content %}

<div class="container" style="margin-top: 10px">
  <div class="row">
    <div class="col text-center">
      <div class="title_data">
        Раунд: {{ fight_data.round_number }}
        <p data-id='{{fight_data.final_status}}' class="check_final_status"></p>
        <p data-id='{{fight_data.fight_id}}' class="check_fight_id"></p>
      </div>
    </div>
  </div>
  
  <div class="row">
    <div class="col text-center">
      <div class="red_fighter_div">
      {{fight_data.red_fighter.participant_first_name}} {{fight_data.red_fighter.participant_last_name}}
        <p></p>
        <button data-id='{{fight_data.fight_id}}' type="button" class="select_red_fighter btn btn-primary">Выбрать</button>
      </div>  
      <p></p>

    </div>
    <div class="col text-center">
      <div class="blue_fighter_div text-center">
      {{fight_data.blue_fighter.participant_first_name}} {{fight_data.blue_fighter.participant_last_name}}
      </div>
      <p></p>
      <button data-id='{{fight_data.blue_fighter_id}}' type="button" class="select_blue_fighter btn btn-primary">Выбрать</button>
    </div>
    
  </div>
</div>          






<script src="https://code.jquery.com/jquery-3.5.1.js"></script>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js"></script>

<script>
    $(document).ready(function() {
    var final_status = $('.check_final_status').data('id');
    var fight_id = $('.check_fight_id').data('id');
    console.log("final status ", final_status)
      console.log("fight_id ", fight_id)
    
      // Обработка нажатия красного бойца в ajax
      // Из ajax мы можем получить только fight_id здесь нет вообще никаких данных из БД. Поэтому получив данные из Бд уходим сразу на раут с обработкой этого fight_id
      $(".red_fighter_div").click('.select_red_fighter_ajax', function(){
        console.log("final status ", final_status)
        if (final_status == "final") {
          window.location.href="{{ url_for('home.finish_red', fight_id=fight_data.fight_id)}}";
        }
        var fight_id = $('.select_red_fighter_ajax').data('id');
        console.log("данные с кнопки ajax", fight_id)
        $.ajax({
        url: '/ajaxfile_red_fighter',
        type: 'post',
        data: {fight_id:fight_id},
        success: function(data){
            $('.red_fighter_div').html(data);
            $('.red_fighter_div').append(data.htmlresponsered);
            $('.blue_fighter_div').html(data);
            $('.blue_fighter_div').append(data.htmlresponseblue);
            $('.title_data').html(data);
            $('.title_data').append(data.htmlresponsetitle);
            
          }
        });

       });

      $('.select_red_fighter').click(function(){
        console.log("final status ", final_status)
        
        if (final_status == "final") {
          window.location.href="{{ url_for('home.finish_red', fight_id=fight_data.fight_id)}}";
        } 

        //var round_number = {{ fight_data.round_number }}
        //var fight_id =  {{ fight_data.fight_id }}

        console.log("fight_id после нажатия c первого боя", {{fight_data.fight_id}})
        $.ajax({
        url: '/ajaxfile_red_fighter',
        type: 'post',
        data: {fight_id:fight_id},
        success: function(data){
            $('.red_fighter_div').html(data);
            $('.red_fighter_div').append(data.htmlresponsered);
            $('.blue_fighter_div').html(data);
            $('.blue_fighter_div').append(data.htmlresponseblue);

          }
        });
        });
        $('.select_blue_fighter').click(function(){
            var blue_fighter_id = $(this).data('id');

            $.ajax({
            url: '/ajaxfile_blue_fighter',
            type: 'post',
            data: {blue_fighter_id: blue_fighter_id},
            // success: function(data){
            //     $('.modal-body').html(data);
            //     $('.modal-body').append(data.htmlresponse);
            //     $('#competition_edit_modal').modal('show');
            // }
          });
        });
     

} );
</script>

{% endblock %}

turnirv4/turnir_project/templates/competition_start.html
{% extends "base.html" %}

{% block title %} Начать турнир {% endblock %}

{% block content %}
<div class="container-fluid" style="margin-top: 10px">
    <div class="row">
        <div class="col">
            <div class="text-center">
                <a href="{{url_for( 'home.competition_create_new' )}}"><button type="button" class="btn btn-outline-info">Начать турнир</button></a>


            </div>
        </div>
    </div>


</div>

{% endblock %}

turnirv4/turnir_project/templates/finish.html
{% extends "base.html" %}

{% block content %}

<div class="container" style="margin-top: 10px">
  <div class="row">
    <div class="col text-center">
      <div>
        Победил {{ winner_data.participant_first_name }} {{ winner_data.participant_last_name }} 
        
      </div>
    </div>
  </div>
</div>          


{% endblock %}

turnirv4/turnir_project/templates/home.html
{% extends "base.html" %}

{% block content %}
homepage
{% endblock %}

turnirv4/turnir_project/templates/response_blue_fighter_div.html
{{fight_data.blue_fighter.participant_first_name}} {{fight_data.blue_fighter.participant_last_name}}

turnirv4/turnir_project/templates/response_red_fighter_div.html
{{fight_data.red_fighter.participant_first_name}} {{fight_data.red_fighter.participant_last_name}}
  <p ></p>
  <button data-id= {{fight_data.fight_id}} type="button" class="select_red_fighter_ajax btn btn-primary" id="internal_button">Выбрать ajax</button>

turnirv4/turnir_project/templates/response_title_div.html
Раунд: {{ fight_data.round_number }}
<p data-id='{{fight_data.final_status}}' class="check_final_status"></p>
<p data-id='{{fight_data.fight_id}}' class="check_fight_id"></p>